### ISSUE TITLE
Do npm-add-scripts logic in JS instead of Python scripts.

### ISSUE THREAD

**Issue by Gregorgeous** [hypermedia-app/creta-template-api#12]
_(from discussion in another place)_ 
@tpluscode suggests that if we are forced to do this logic in scripts anyway, let's just do it in .JS "natively" instead of this `python file->in-python shell->in-shell npm` approach here.
(Will require some extra work with npm dependencies so let's not do it in this PR) 
Example:  https://github.com/coleww/npm-add-script#api

_Originally posted by @Gregorgeous in https://github.com/hypermedia-app/creta-template-api/pull/11#discussion_r841261428_

**Comment by tpluscode** [comment]
I finally opted to do in-place replacement using [json](https://npm.im/json)

This removes the need to wrestle with env variable expansion and additional scripts
